force-app/main/default/objects/Opportunity/fields/Competitor_1__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1__c</fullName>
    <label>Competitor 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Yahoo!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_2__c.field-meta.xml
<CustomField>
    <fullName>Competitor_2__c</fullName>
    <label>Competitor 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Yahoo!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_3__c.field-meta.xml
<CustomField>
    <fullName>Competitor_3__c</fullName>
    <label>Competitor 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Yahoo!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AA_CodingTechniques/main/default/classes/LeadingCompetitorTest.cls
@IsTest 
public class LeadingCompetitorTest {
    @IsTest static void LeadingCompetitorTest() {
        Opportunity opp = new Opportunity(
            Name                  = 'Test',
            CloseDate             = Date.today() + 30,
            StageName             = 'Prospecting',
            Competitor_1__c       = 'Google',
            Competitor_1_Price__c = 500,
            Competitor_2__c       = 'Oracle',
            Competitor_2_Price__c = 400,
            Competitor_3__c       = 'Salesforce',
            Competitor_3_Price__c = 300
        );    
        insert opp;
        
    }
}